# Uncomment the next line to define a global platform for your project
# platform :ios, '1.0'

target 'HHMasonryDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HHMasonryDemo

  pod 'Masonry'

end
